
class Interpretador:

    notas_midi = {
        'A': '69',   # La
        'B': '71',   # Si
        'C': '60',   # Do
        'D': '62',   # Re
        'E': '64',   # Mi
        'F': '65',   # Fa
        'G': '67',   # Sol
        'H': '70'    # Si Bemol
    }

    gm_instruments = {
        'Piano Acustico Grand': '00',
        'Piano Acustico Brilhante': '01',
        'Piano Eletrico Grand': '02',
        'Piano Honky-tonk': '03',
        'Piano Eletrico 1': '04',
        'Piano Eletrico 2': '05',
        'Cravo': '06',
        'Clavicordio': '07',
        'Celesta': '08',
        'Glockenspiel': '09',
        'Caixa de Musica': '0A',
        'Vibrafone': '0B',
        'Marimba': '0C',
        'Xilofone': '0D',
        'Sinos Tubulares': '0E',
        'Dulcimer': '0F',
        'Orgao de Tiras': '10',
        'Orgao Percussivo': '11',
        'Orgao Rock': '12',
        'Orgao de Igreja': '13',
        'Orgao de Palheta': '14',
        'Acordeao': '15',
        'Gaita': '16',
        'Acordeao Tango': '17',
        'Violao (nylon)': '18',
        'Violao (aco)': '19',
        'Guitarra Eletrica (jazz)': '1A',
        'Guitarra Eletrica (clean)': '1B',
        'Guitarra Eletrica (abafada)': '1C',
        'Guitarra Overdriven': '1D',
        'Guitarra Distorcida': '1E',
        'Harmonicos de Guitarra': '1F',
        'Baixo Acustico': '20',
        'Baixo Eletrico (dedo)': '21',
        'Baixo Eletrico (palheta)': '22',
        'Baixo Sem Trastes': '23',
        'Slap Bass 1': '24',
        'Slap Bass 2': '25',
        'Baixo Sintetizado 1': '26',
        'Baixo Sintetizado 2': '27',
        'Violino': '28',
        'Viola': '29',
        'Violoncelo': '2A',
        'Contrabaixo': '2B',
        'Cordas Tremolo': '2C',
        'Cordas Pizzicato': '2D',
        'Harpa Orquestral': '2E',
        'Timpanos': '2F',
        'Conjunto de Cordas 1': '30',
        'Conjunto de Cordas 2': '31',
        'Cordas Sintetizadas 1': '32',
        'Cordas Sintetizadas 2': '33',
        'Coro Aahs': '34',
        'Voz Oohs': '35',
        'Voz Sintetizada': '36',
        'Orchestra Hit': '37',
        'Trompete': '38',
        'Trombone': '39',
        'Tuba': '3A',
        'Trompete Abafado': '3B',
        'Trompa Francesa': '3C',
        'Secao de Metais': '3D',
        'Metais Sintetizados 1': '3E',
        'Metais Sintetizados 2': '3F',
        'Sax Soprano': '40',
        'Sax Alto': '41',
        'Sax Tenor': '42',
        'Sax Baritono': '43',
        'Oboe': '44',
        'Corne Ingles': '45',
        'Fagote': '46',
        'Clarinete': '47',
        'Piccolo': '48',
        'Flauta': '49',
        'Flauta Doce': '4A',
        'Flauta de Pan': '4B',
        'Garrafa Soprada': '4C',
        'Shakuhachi': '4D',
        'Apito': '4E',
        'Ocarina': '4F',
        'Lead 1 (quadrado)': '50',
        'Lead 2 (dente de serra)': '51',
        'Lead 3 (caliope)': '52',
        'Lead 4 (chiff)': '53',
        'Lead 5 (charang)': '54',
        'Lead 6 (voz)': '55',
        'Lead 7 (quintas)': '56',
        'Lead 8 (baixo + lead)': '57',
        'Pad 1 (new age)': '58',
        'Pad 2 (quente)': '59',
        'Pad 3 (polissintetizador)': '5A',
        'Pad 4 (coral)': '5B',
        'Pad 5 (arcado)': '5C',
        'Pad 6 (metalico)': '5D',
        'Pad 7 (halo)': '5E',
        'Pad 8 (varredura)': '5F',
        'FX 1 (chuva)': '60',
        'FX 2 (trilha sonora)': '61',
        'FX 3 (cristal)': '62',
        'FX 4 (atmosfera)': '63',
        'FX 5 (brilho)': '64',
        'FX 6 (goblins)': '65',
        'FX 7 (ecos)': '66',
        'FX 8 (ficcao cientifica)': '67',
        'Sitar': '68',
        'Banjo': '69',
        'Shamisen': '6A',
        'Koto': '6B',
        'Kalimba': '6C',
        'Gaita de Fole': '6D',
        'Viola Caipira': '6E',
        'Shanai': '6F',
        'Sino Tilintante': '70',
        'Agogo': '71',
        'Tambores de Aco': '72',
        'Bloco de Madeira': '73',
        'Taiko': '74',
        'Tom Melodico': '75',
        'Tambor Sintetizado': '76',
        'Prato Reverso': '77',
        'Ruido de Traste': '78',
        'Ruido de Respiração': '79',
        'Mar': '7A',
        'Passaros': '7B',
        'Telefone Tocando': '7C',
        'Helicoptero': '7D',
        'Aplausos': '7E',
        'Tiro': '7F'
    }

