
class Interpretador:
    def __init__(self):
        self.notas_midi = {
            'A': 21,   # La (A0 = MIDI 21)
            'B': 23,   # Si (B0 = MIDI 23)
            'C': 12,   # Do (C0 = MIDI 12)
            'D': 14,   # Re (D0 = MIDI 14)
            'E': 16,   # Mi (E0 = MIDI 16)
            'F': 17,   # Fa (F0 = MIDI 17)
            'G': 19,   # Sol (G0 = MIDI 19)
            'H': 22,    # Si Bemol (Bb0 = MIDI 22)
            'M': 27
        }

        self.gm_intruments_comando = {
                '!': 21,
                'O': 109,
                'o': 109,
                'U': 109,
                'u': 109,
                'I': 109,
                'i': 109,
                ',': 19,
                ';': 14
                }

        gm_instruments = {
            'Piano Acustico Grand': 0,
            'Piano Acustico Brilhante': 1,
            'Piano Eletrico Grand': 2,
            'Piano Honky-tonk': 3,
            'Piano Eletrico 1': 4,
            'Piano Eletrico 2': 5,
            'Cravo': 6,
            'Clavicordio': 7,
            'Celesta': 8,
            'Glockenspiel': 9,
            'Caixa de Musica': 10,
            'Vibrafone': 11,
            'Marimba': 12,
            'Xilofone': 13,
            'Sinos Tubulares': 14,
            'Dulcimer': 15,
            'Orgao de Tiras': 16,
            'Orgao Percussivo': 17,
            'Orgao Rock': 18,
            'Orgao de Igreja': 19,
            'Orgao de Palheta': 20,
            'Acordeao': 21,
            'Gaita': 22,
            'Acordeao Tango': 23,
            'Violao (nylon)': 24,
            'Violao (aco)': 25,
            'Guitarra Eletrica (jazz)': 26,
            'Guitarra Eletrica (clean)': 27,
            'Guitarra Eletrica (abafada)': 28,
            'Guitarra Overdriven': 29,
            'Guitarra Distorcida': 30,
            'Harmonicos de Guitarra': 31,
            'Baixo Acustico': 32,
            'Baixo Eletrico (dedo)': 33,
            'Baixo Eletrico (palheta)': 34,
            'Baixo Sem Trastes': 35,
            'Slap Bass 1': 36,
            'Slap Bass 2': 37,
            'Baixo Sintetizado 1': 38,
            'Baixo Sintetizado 2': 39,
            'Violino': 40,
            'Viola': 41,
            'Violoncelo': 42,
            'Contrabaixo': 43,
            'Cordas Tremolo': 44,
            'Cordas Pizzicato': 45,
            'Harpa Orquestral': 46,
            'Timpanos': 47,
            'Conjunto de Cordas 1': 48,
            'Conjunto de Cordas 2': 49,
            'Cordas Sintetizadas 1': 50,
            'Cordas Sintetizadas 2': 51,
            'Coro Aahs': 52,
            'Voz Oohs': 53,
            'Voz Sintetizada': 54,
            'Orchestra Hit': 55,
            'Trompete': 56,
            'Trombone': 57,
            'Tuba': 58,
            'Trompete Abafado': 59,
            'Trompa Francesa': 60,
            'Secao de Metais': 61,
            'Metais Sintetizados 1': 62,
            'Metais Sintetizados 2': 63,
            'Sax Soprano': 64,
            'Sax Alto': 65,
            'Sax Tenor': 66,
            'Sax Baritono': 67,
            'Oboe': 68,
            'Corne Ingles': 69,
            'Fagote': 70,
            'Clarinete': 71,
            'Piccolo': 72,
            'Flauta': 73,
            'Flauta Doce': 74,
            'Flauta de Pan': 75,
            'Garrafa Soprada': 76,
            'Shakuhachi': 77,
            'Apito': 78,
            'Ocarina': 79,
            'Lead 1 (quadrado)': 80,
            'Lead 2 (dente de serra)': 81,
            'Lead 3 (caliope)': 82,
            'Lead 4 (chiff)': 83,
            'Lead 5 (charang)': 84,
            'Lead 6 (voz)': 85,
            'Lead 7 (quintas)': 86,
            'Lead 8 (baixo + lead)': 87,
            'Pad 1 (new age)': 88,
            'Pad 2 (quente)': 89,
            'Pad 3 (polissintetizador)': 90,
            'Pad 4 (coral)': 91,
            'Pad 5 (arcado)': 92,
            'Pad 6 (metalico)': 93,
            'Pad 7 (halo)': 94,
            'Pad 8 (varredura)': 95,
            'FX 1 (chuva)': 96,
            'FX 2 (trilha sonora)': 97,
            'FX 3 (cristal)': 98,
            'FX 4 (atmosfera)': 99,
            'FX 5 (brilho)': 100,
            'FX 6 (goblins)': 101,
            'FX 7 (ecos)': 102,
            'FX 8 (ficcao cientifica)': 103,
            'Sitar': 104,
            'Banjo': 105,
            'Shamisen': 106,
            'Koto': 107,
            'Kalimba': 108,
            'Gaita de Fole': 109,
            'Viola Caipira': 110,
            'Shanai': 111,
            'Sino Tilintante': 112,
            'Agogo': 113,
            'Tambores de Aco': 114,
            'Bloco de Madeira': 115,
            'Taiko': 116,
            'Tom Melodico': 117,
            'Tambor Sintetizado': 118,
            'Prato Reverso': 119,
            'Ruido de Traste': 120,
            'Ruido de Respiração': 121,
            'Mar': 122,
            'Passaros': 123,
            'Telefone Tocando': 124,
            'Helicoptero': 125,
            'Aplausos': 126,
            'Tiro': 127
        }


